position_list = [
    'Beverage',
    'Freelance',
    'Overlord',
    'Animal',
    'Head of',
    'Wizard',
    'Problem Wrangler',
    'Director of',
    'Retail',
    'Alchemist',
    'Rockstar',
    'Manager',
    'Mentor',
    'Chief',
    'Life Coach',
    'Executive Manager of',
    'Collector of',
    'Co-Founder of',
    'Manager',
    'Officer',
    'Travel Agent',
    'Psychologist',
    'Santa Claus',
    'Ambassador of',
    'In Charge of',
    'Hero',
]

