society_list = [
    'Mordor srl',
    'Hogwarts spa',
    'ECorp',
    'Dreams snc',
    'Shelby LTD',
    'Planet of the Grapes',
    'Lord of the Fries',
    'Hurry Curry',
    'Eggcellent Eats',
    'Thai Tanic',
    'Wok This Way',
    'Pho Shizzle',
    'Mustard’s Last Stand',
    'Life of Pie',
    'Basic Kneads Pizza',
    'Earth Wind And Flour',
    '9021 Pho',
    'Sweet Cheezus',
    'Fishcoteque',
    'Grill \'Em All',
    'Mind Serenade',
    'Shadow Barbarians',
    'Power Assault Doomsters',
    'The Cyco Paths',
    'Float Away',
    'Long Long Ago',
    'Char coal',
    'Cadabra',
    'n!',
    'Login Not Found',
    'BitCoin',
]

